### PR TITLE
Fix issue #180: ctrl+plus shortcut key zoom in is invalid

### LINKED ISSUE #180: ctrl + won't zoom in, but ctrl - will work

### PR DESCRIPTION
**Pull request by raymond-ley**
Signed-off-by: Raymond Ley [raymond-ley@qq.com](mailto:raymond-ley@qq.com)

## Description

1. Fix issue #180: ctrl+plus shortcut key zoom in is invalid
2. Incidentally, add the process of deleting resource files after extracting files from the installation shell script

## Related Issues

Close #180

### CODE REVIEW

**Comment by abbychau** [comment]
This will instead disable the numpad plus.
let's implement multiple hotkeys.

**Comment by raymond-ley** [comment]
> This will instead disable the numpad plus. let's implement multiple hotkeys.

Thank you for your suggestion. I changed it to multiple hotkeys:)

**Comment by truell20** [comment]
looks good! ty ty

**Comment by shouya** [comment]
This change results in Cursor running in the background stealing `Ctrl+Plus` from the foreground applications.

**Comment by raymond-ley** [comment]
> This change results in Cursor running in the background stealing from the foreground applications.`Ctrl+Plus`

Thank you for your feedback on this issue. I am actively repairing this issue:)

**Comment by raymond-ley** [comment]
> This change results in Cursor running in the background stealing `Ctrl+Plus` from the foreground applications.

This issue has been fixed by Merge # 257 :)

**Comment by shouya** [comment]
Thank you for the prompt fix!

**Pull request merged**
