### PR TITLE
Add support of themes

### PR DESCRIPTION
**Pull request by abbychau**
Refs:
https://github.com/getcursor/cursor/issues/25
https://github.com/getcursor/cursor/issues/60
https://github.com/getcursor/cursor/issues/103

### CODE REVIEW

**Comment by truell20** [comment]
thanks for starting on this @abbychau. ideally we'd implement themes by changing the styling of the components around codemirror as well, thought this will require a refactor of our css (which really shouldn't just be in one style sheet).

if you or anyone is interested in trying your hand at that, feel free! otherwise, i'll get to that eventually and can start from the work you did in this branch.

**Comment by abbychau** [comment]
sure. let me add the support of them change of the sidebar and tabbar as well.

**Comment by truell20** [comment]
ooh that'd be awesome

**Comment by IOLOII** [comment]
> sure. let me add the support of them change of the sidebar and tabbar as well.

The vscode sidebar drag effect has been added #345

**Comment by truell20** [comment]
Thanks for working on this @abbychau @IOLOII, the newest VSCode-based version of Cursor should have theme support

**Pull request closed without merging**
