### PR TITLE
Fixes #236

### LINKED ISSUE #236: When opening Terminal, the root path should be at the root path of the project.
as title.

(maybe related to https://github.com/getcursor/cursor/issues/232 too)

### PR DESCRIPTION
**Pull request by dvlpjrs**
Fixes #236

### CODE REVIEW

**Comment by truell20** [comment]
hey! thanks for doing this. does it not open to the project path in the latest version (v0.1.9)?

**Comment by dvlpjrs** [comment]
When opening new folders through the menu>file>open folder, the terminal's path either defaults to the root directory or remains at the previous folder's location.

**Review by ahmadank — CHANGES_REQUESTED** [review]
For the terminal.ts file, you should add  `ptyProcess.kill('SIGINT')` incase the user was running a proccess

**Comment by truell20** [comment]
Thank you for doing this 🙂 Should be fixed in the new vscodeium-based version of Cursor

**Pull request closed without merging**
