### PR TITLE
Add: Vue.js syntax support 

### PR DESCRIPTION
**Pull request by boxizen**
closes https://github.com/getcursor/cursor/issues/266

I have added the vuejs language pack on codemirror.
For details, check this [PR](https://github.com/codemirror/language-data/pull/3).

Just need to update the next version to take effect, the support of VueJS is as follows.

image

### CODE REVIEW

**Comment by fischeversenker** [comment]
Note from a random stranger:
As far as I can tell, the only relevant change in this PR is the version bump in the `package.json` and the corresponding changes in the `package-lock.json`. Everything else is just noise that makes this PR a lot harder to review. If I was a maintainer, I would ask you to remove the unrelated changes.
If you agree with me, you might want to revert these changes to help fellow contributors, @boxizen :pray:

**Comment by boxizen** [comment]
> Note from a random stranger: As far as I can tell, the only relevant change in this PR is the version bump in the `package.json` and the corresponding changes in the `package-lock.json`. Everything else is just noise that makes this PR a lot harder to review. If I was a maintainer, I would ask you to remove the unrelated changes. If you agree with me, you might want to revert these changes to help fellow contributors, @boxizen 🙏

You're right, but the author added a code formatting check last night, and if I don't prettier the rest of the code, it won't pass the check

**Comment by fischeversenker** [comment]
Thanks for the feedback. I now found https://github.com/getcursor/cursor/issues/271 and saw that you are already involved there.
Sorry for interfering 🙈
Keep on being awesome 🙌

**Comment by truell20** [comment]
thank you for this!!!

**Pull request merged**
