### PR TITLE
Support i18n capabilities

### PR DESCRIPTION
**Pull request by boxizen**
# 01 Requirements

Recently, many people in China have heard about cursor through tiktok or science and technology information. In order to help developers in other regions use cursor better, and to promote it in Asia, as a Chinese and Japanese speaker, I'd love to contribute to the i18n capabilities of cursor.

This PR is the i18n capability I added, I will list the main changes below to help you review.

# 02 Changes

## Major Files

`src /i18n.ts`

Added two main plugins, `react-i18next` and `i18next-http-backend`, where http-backend is used for the internationalization settings of electron (mainly menu bar), and the other is used for the front end.

`src/main/main.ts`

Added the language initialization settings of the Electron part, and listened to the notification event of the language change on the front-end side at the same time.

The label text of Electron's menu cannot be updated dynamically, so it is necessary to re-execute `setApplicationMenu` every time the language changes, here I wrap the menu list with the `getMenuTemplate` function.

`src/features/globalSlice.ts`

Added the acquisition of cached language setting items, and initialized i18n at the front end.

`src/components/settingsPane.tsx`

Added language switching settings switch panel, and switching events.

## Languages

- [x] Chinese
- [x] Japanese
- [ ] Thai
- [ ] Vietnamese
- [ ] Korean
- [ ] Russian

## Dependencies

* i18next: "^22.4.13"
* react-i18next: "^12.2.0"
* i18next-http-backend: "^2.2.0"

# 03 Effects

https://user-images.githubusercontent.com/6027456/228432697-fd1e4c53-2044-41db-9454-252de6232dae.mp4

# 04 More

With the increase of language packs in the future, the language configuration file can be loaded asynchronously to improve the loading performance of the first screen.

### CODE REVIEW

**Review by IOLOII — COMMENTED** [review]
Learned

**Comment by besoshanjun** [comment]
期待...

**Comment by truell20** [comment]
Are you able to use i18n in the new vscodeium-based version of Cursor?

**Comment by truell20** [comment]
Perhaps using: https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally ?

**Pull request closed without merging**
